name: OIDC Test
on: [push]

permissions:
  id-token: write  # This is mandatory for OIDC
  contents: read

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::549368061164:role/GitHub-OIDC-ZeroTrust-Role
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity
